### ISSUE TITLE
(Bug?) Close the app before running the patcher

### ISSUE THREAD

**Issue by SyphereyD10** [nekusu/tidal-enhanced-patcher#1]
Hello, as the title says everytime i try to run the **node patch** command it gives me the following output

> TIDAL Enhanced Patcher - https://github.com/nekusu
> Close the app before running the patcher!

Following the usage instructions on the main page:

1. I have installed the latest version available of [nvm (1.19.0)](https://github.com/coreybutler/nvm-windows/releases/latest)
2. I told nvm to use the latest **LTS version:** [(18.12.0)](https://nodejs.org/en/) of node.js available
3. I have tried to run the command: `git clone git@github.com:nekusu/tidal-enhanced-patcher.git` but it gave me **acces denied** as output
4. So i cloned the rep by using `git clone https://github.com/nekusu/tidal-enhanced-patcher.git`
5. Then i moved to the main folder and tried to use the command **node patch**

- [x] I've closed tidal and made sure no process of the exe were executing in background
- [x] I've closed Discord and related threads
- [x] I've tried to run the command just after i've restarted my pc but I still get the same error.

**Comment by nekusu** [comment]
Hello, sorry for the delay. Thank you for leaving a well detailed issue.
I imagined that the way to check if the process was running was going to give problems at some point, I'll push a fix in a few moments. Let me know if you have any other problems.

**Comment by SyphereyD10** [comment]
Hello!
Thanks for helping me, with the latest fix now everything works correctly!
Have a good day.
