### ISSUE TITLE
Changing Tidal's volume from Windows Volume Mixer or an external app

### ISSUE THREAD

**Issue by Epacik** [nekusu/tidal-enhanced-patcher#2]
Is it possible to make Tidal change it's volume (the one near the quality selector) according to the volume set in Windows Volume Mixer?
If not, is it possible to make some kind of "API" that could let other apps control Tidal's volume?

Currently changing volume within Tidal changes it's volume in Windows' Volume Mixer, but changing volume in Volume Mixer does not change a value of the volume slider in Tidal.
If you'd try to change Tidal's volume from Windows' Volume Mixer the loudness of currently playing song would change, but Tidal will reset it as soon as:
- song is paused and resumed, 
- rewound to the start using "Previous" button, 
- or changed

**Comment by nekusu** [comment]
I've spent some time looking at the source code to figure out how the volume control works, but this is completely outside my current knowledge, although I think it's possible.

It would be very helpful if some experienced developer could help us with this. I apologize, I don't really have time to work on features this big at the moment.

**Comment by Epacik** [comment]
I may try to investigate it myself if I'll get some free time

**Comment by Epacik** [comment]
It seems like this improvement may not be needed after all.
After a recent update Tidal disables in-app volume control after changing volume in a Windows' Volume Mixer, and relies solely on volume set by mixer.
I'll reopen this issue if that'd be broken again.
